spring:
  #mariaDB
  datasource:
    url: jdbc:mariadb://localhost/userDetails # you should create a mariaDB in local
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  #jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false

  #redis
  data:
    redis:
      host: localhost
      port: 6379


  security:
    user:
      name: a
      password: a



